### ISSUE TITLE
Zend Extension Thread Safety: disabled

### ISSUE THREAD

**Issue by miraculix70** [miraculix70/cryptomate64#3]
## Auszug aus phpsysinfo():

```
PHP Extension => 20190902
Zend Extension => 320190902
Zend Extension Build => API320190902,NTS
PHP Extension Build => API20190902,NTS
Debug Build => no
Thread Safety => disabled
Zend Signal Handling => enabled
Zend Memory Manager => enabled
Zend Multibyte Support => provided by mbstring
IPv6 Support => enabled
DTrace Support => available, disabled

```

## warum disabled?
Achtung
Zend Thread Safety cannot be enabled post build; it is a build time configuration option.
Zend Thread Safety https://www.php.net/manual/de/parallel.setup.php

## TODO

- [ ] PHP auf obelix neu compilieren mit aktiviertem Zend Thread Safety
- [ ] ggf release-upgrade und
- [ ] PHP upgrade auf V8

**Comment by miraculix70** [comment]
`betrifft obelix`
